services:
  backend-template:
    build:
      context: backend
    env_file:
      - backend/.env.docker
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "httpx", "http://localhost:8000/health", "--method", "GET"]
      interval: 30s
      timeout: 30s
      retries: 1
      start_period: 10s
    depends_on:
      mongodb:
        condition: service_healthy
