services:
  backend-template:
    build:
      context: backend
    env_file:
      - backend/.env.docker.dev
    volumes:
      - type: bind
        source: backend
        target: /usr/app/backend
    ports:
      - 8000:8000
    # TODO no curl in Alpine
    healthcheck:
      test: ["CMD", "echo", "1"] #"--fail", "http://localhost:8000/health"]
      interval: 30s
      timeout: 30s
      retries: 1
      start_period: 10s
    depends_on:
      mongodb:
        condition: service_healthy
