# https://docs.docker.com/go/compose-spec-reference/

# For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
# TODO how to separate into dev and prod runs?
services:
  backend-dev:
    profiles:
      - dev
    extends:
      file: common.yaml
      service: backend-template
    build:
      target: dev
  backend-prod:
    profiles:
      - prod
    extends:
      file: common.yaml
      service: backend-template
    build:
      target: prod

  frontend-dev:
    profiles:
      - dev
    build:
      context: frontend
      target: dev
    environment:
      NODE_ENV: development
    volumes:
      - type: bind
        source: frontend/index.html
        target: /usr/app/frontend/index.html
      - type: bind
        source: frontend/src
        target: /usr/app/frontend/src
    ports:
      - 5173:5173
    depends_on:
      backend-dev:
        condition: service_healthy
  frontend-prod:
    profiles:
      - prod
    build:
      context: frontend
      target: prod
    environment:
      NODE_ENV: production
    ports:
      - 5173:80
    depends_on:
      backend-prod:
        condition: service_healthy
  mongodb:
    image: mongodb/mongodb-community-server:6.0.23-ubuntu2204
    restart: always
    # user: postgres
    # secrets:
    #   - db-password
    env_file:
      - backend/.env.docker
    # environment:
    #   - MONGODB_INITDB_ROOT_USERNAME_FILE=/run/secrets/db-username
    #   - MONGODB_INITDB_ROOT_PASSWORD_FILE=/run/secrets/db-password
    #   # TODO make this secure MONGODB_INITDB_ROOT_USERNAME_FILE,MONGODB_INITDB_ROOT_PASSWORD_FILE
    #   - MONGODB_INITDB_ROOT_USERNAME=user
    #   - MONGODB_INITDB_ROOT_PASSWORD=pass
    # volumes:
    #   - type: bind
    #     source: ./data
    #     target: /data/db
    # environment:
    #   - POSTGRES_DB=example
    #   - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh $$MONGODB_URI --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    # secrets:
    #   - db-password
    #   - db-username
# secrets:
#   db-password:
#     file: secrets/db-password.txt
#   db-username:
#     file: secrets/db-username.txt
# # volumes:
#   db-data:
